<?php

/**
 * Implements hook_page_attachments_alter().
 */
function drupal_gpt_page_attachments_alter(array &$attachments) {
    $config = \Drupal::config('drupal_gpt.settings');
    $allowed_paths = [];
    $category = "";
    $urls = $config->get("urls");
    foreach($urls as $url){
        $allowed_paths[] = $url["url"];
        $category = $url["category"];
    }

    $current_path = \Drupal::service('path.current')->getPath();
    if (in_array($current_path, $allowed_paths)) {
        $attachments['#attached']['library'][] = 'drupal_gpt/drupal-gpt-hook';
        $attachments['#attached']['drupalSettings']['drupal_gpt']['category'] = $category;
    }
}
