drupal_gpt.settings:
  type: config_object
  label: 'DrupalGPT configuration settings'
  mapping:
    openai_key:
      type: text
      label: 'Your OpenAI key'
    openai_model:
      type: text
      label: 'What model do you want the chatbot to use?'
    max_requests_per_session:
      type: integer
      label: 'How many messages can the user send before killing the session?'
    max_requests_per_minute:
      type: integer
      label: 'How many messages can the user send per minute?'
    cleanup_after_minutes:
      type: integer
      label: 'A session will be declared inactive if a user hasn't sent a message in this many minutes.'