drupal_gpt.settings:
  type: config_object
  label: 'DrupalGPT configuration settings'
  mapping:
    urls:
      type: sequence
      label: 'URLs'
      sequence:
          type: mapping
          label: 'URL entry'
          mapping:
            url:
              type: string
              label: 'URL'
            category:
              type: string
              label: 'Category'
    chatbot_categories:
      type: sequence
      label: 'Categories'
      sequence:
        - type: mapping
          label: 'Category'
          mapping:
            name:
              type: string
              label: 'Name'
    chatbot_context:
      type: sequence
      label: 'Contexts'
      sequence:
          type: mapping
          label: 'Context Entry'
          mapping:
            uuid:
              type: list
              label: 'Category'
            number_of_context:
              type: string
              label: 'Category'
            
    num_urls:
      type: integer
      label: 'Number of URLs'
    openai_key:
      type: text
      label: 'Your OpenAI key'
    openai_model:
      type: text
      label: 'What model do you want the chatbot to use?'
    openai_model_accuracy:
      type: text
      label: 'What model do you want the chatbot to use for determining accuracy?'
    pinecone_environment:
      type: text
      label: 'What is the environment for your index?'
    pinecone_key:
      type: text
      label: 'Your pinecone key.'
    pinecone_index_url:
      type: text
      label: 'The url for the index of your pinecone database you wish to search.'
    max_requests_per_session:
      type: integer
      label: 'How many messages can the user send before killing the session?'
    max_requests_per_minute:
      type: integer
      label: 'How many messages can the user send per minute?'
    cleanup_after_minutes:
      type: integer
      label: 'A session will be declared inactive if a user hasnt sent a message in this many minutes.'
    enabled_accuracy_meter:
      type: boolean
      label: 'Enable the accuarcy meter'