<?php

namespace Drupal\drupal_gpt\Controller;

use Symfony\Component\HttpFoundation\JsonResponse;
use Drupal\Core\Controller\ControllerBase;

class TestController extends ControllerBase {
    
    private SessionController $session_controller;
    

    function __construct(){
        $this->session_controller = new SessionController();
    }

    public function testLines(){

        $messages = [
            "What is the mission of the BYU McKay School of Education?",
            "What are the different programs offered by the school?",
            "What are the admission requirements for the school?",
            "What are the scholarships and financial aid available to students?",
            "What are the facilities and resources available to students?",
            "What are the career opportunities for graduates of the school?",
            "What is the student body like at the school?",
            "What is the faculty like at the school?",
            "What is the cost of attendance at the school?",
            "What is the location of the school?",
            "What is the history of the school?",
            "What are the rankings of the school?",
            "What are the accreditations of the school?",
            "What are the research strengths of the school?",
            "What are the community service opportunities available to students?",
            "What are the extracurricular activities available to students?",
            "What are the clubs and organizations available to students?",
            "What are the sports teams available to students?",
            "What are the housing options available to students?",
            "What are the dining options available to students?",
            "What are the transportation options available to students?",
            "What are the safety and security measures in place at the school?",
            "What are the health and wellness resources available to students?",
            "What are the career services available to students?",
            "What are the alumni services available to students?",
            "What are the international student services available to students?",
            "What are the disabilities services available to students?",
            "What are the other services available to students?",
            "What are the religious services available to students?",
            "How do I schedule an appointment with an academic advisor in the McKay School of Education?",
            "Can you help me book a meeting with an academic advisor?",
            "I need to talk to an academic advisor, what's the process for that?",
            "Can you assist me in connecting with a McKay School academic advisor?",
            "When are the available times to meet with an academic advisor?",
            "What's the best way to set up an appointment with a McKay School advisor?",
            "How can I get in touch with an academic advisor from the McKay School?",
            "Is there a way to schedule an academic advising session online?",
            "Can I meet with an academic advisor to discuss my course selection?",
            "I want to speak with an academic advisor ASAP, what should I do?",
            "Can you provide me with the contact information for a McKay School academic advisor?",
            "What are the options for meeting with an academic advisor in the McKay School?",
            "Can I book a virtual meeting with a McKay School academic advisor?",
            "I need to plan my academic schedule, who should I talk to?",
            "Are there drop-in advising services available in the McKay School?",
            "How do I find an academic advisor who specializes in my field of study?",
            "Can I meet with an academic advisor during the weekends?",
            "How soon can I meet with an academic advisor in the McKay School?",
            "Is there a limit to the number of advising sessions I can have?",
            "Can I speak with an academic advisor on the phone?",
            "I'm considering changing my major, can an advisor assist me with that?",
            "Can I get help from an advisor to plan my education degree program?",
            "What's the availability of academic advisor appointments during holidays?",
            "Can you tell me the McKay School academic advisor's office hours?",
            "How do I reschedule an appointment with my academic advisor?",
            "Can an academic advisor help me with creating a graduation plan?",
            "Is there a cost associated with meeting with a McKay School academic advisor?",
            "Can I get advice from an advisor regarding graduate school options?",
            "I need academic advising for understanding degree requirements, who do I talk to?",
            "Can I meet with an academic advisor to discuss my academic progress?",
            "What's the procedure for meeting with an academic advisor for the first time?",
            "Can you recommend an advisor who understands the McKay School's programs?",
            "How do I cancel an appointment with my academic advisor?",
            "I'm interested in studying abroad, can an advisor guide me on that?",
            "Can I talk to an academic advisor about scholarship opportunities?",
            "Is there a McKay School advisor who specializes in student teaching?",
            "Can an academic advisor assist me with planning my practicum or internship?",
            "I need advice from an advisor about research opportunities in education, who should I see?",
            "Can I meet with an academic advisor to discuss my education career goals?",
            "What's the procedure for applying for an academic scholarship in the McKay School?",
            "Can I speak with an academic advisor about career options in education?",
            "How can an academic advisor assist me with planning my teaching certification exams?",
            "Can I get help from an advisor for understanding the McKay School's degree requirements?",
            "Can I talk to an academic advisor about opportunities for graduate assistantships?",
            "I need academic advising for understanding the Honors Program requirements, who do I talk to?",
            "Can I meet with an academic advisor to discuss opportunities for academic enrichment?",
            "What are the resources available to McKay School students for academic support?",
            "How can an advisor support me with creating a balanced schedule for the upcoming semester?",
            "Can I get help from an advisor for understanding academic progress reports?",
            "Can I speak with an academic advisor about opportunities for presenting research at conferences in education?",
            "How can an academic advisor guide me on preparing for graduate school applications in education?",
            "I need academic advising for understanding prerequisites for specific courses, who do I talk to?",
            "Can I get help from an advisor for understanding the requirements for joining the McKay School's honors society?",
            "What resources are available to McKay School students for academic and career development?",
            "Can an academic advisor guide me on resources and strategies for academic success, such as tutoring and study groups?",
            "Can I meet with an academic advisor to discuss summer course options?",
            "Can an advisor help me with planning my course schedule for my teaching certification?",
            "I need academic advising for understanding prerequisites, who do I talk to?",
            "How can an academic advisor support me with setting academic goals for the semester?",
            "Can I get help from an advisor for understanding academic policies?",
            "Can I talk to an academic advisor about transfer credits and requirements?",
            "How can an academic advisor help me with academic probation or dismissal?",
            "Can I meet with an advisor for academic support and study strategies?",
            "I need academic advising for understanding credit hours and load requirements, who should I see?",
            "Can an academic advisor assist me with course registration?",
            "What's the process for declaring a major in the McKay School of Education?",
            "Can I talk to an advisor about the prerequisites for graduate programs?",
            "How do I find an academic advisor who understands my cultural background?",
            "Can I get help from an advisor for understanding the General Education requirements?",
            "Can I meet with an academic advisor to discuss options for joining student organizations related to education?",
            "I need academic advising for understanding the requirements for a minor in education?",
            "Can an academic advisor guide me on opportunities for undergraduate research in education?",
            "What's the process for meeting with an academic advisor for transfer students?",
            "Can I get help from an advisor for understanding the McKay School's graduation requirements and preparing for graduation?",
            "Can I speak with an academic advisor about opportunities for graduate programs in education?",
            "How can an academic advisor assist me with understanding my degree audit report?",
            "I need academic advising for understanding the process for academic appeals.",
            "Can I meet with an advisor to discuss options for joining the McKay School's honors program?",
            "What's the procedure for changing my major within the McKay School?",
            "Can an advisor help me with planning my course schedule for my teaching certification?",
            "I need academic advising for understanding prerequisites, who do I talk to?",
            "How can an academic advisor support me with setting academic goals for the semester?",
            "Can I get help from an advisor for understanding academic policies?",
            "Can I talk to an academic advisor about transfer credits and requirements?",
            "How can an academic advisor help me with academic probation or dismissal?",
            "Can I meet with an advisor for academic support and study strategies?",
            "I need academic advising for understanding credit hours and load requirements, who should I see?",
            "Can an academic advisor assist me with course registration?",
            "What's the process for declaring a major in the McKay School of Education?",
            "Can I talk to an advisor about the prerequisites for graduate programs?",
            "How do I find an academic advisor who understands my cultural background?",
            "Can I get help from an advisor for understanding the General Education requirements?",
            "Can I meet with an academic advisor to discuss options for joining student organizations related to education?",
            "I need academic advising for understanding the requirements for a minor in education?",
            "Can an academic advisor guide me on opportunities for undergraduate research in education?",
            "What's the process for meeting with an academic advisor for transfer students?",
            "Can I get help from an advisor for understanding the McKay School's graduation requirements and preparing for graduation?",
            "Can I speak with an academic advisor about opportunities for graduate programs in education?",
            "How can an academic advisor assist me with understanding my degree audit report?",
            "I need academic advising for understanding the process for academic appeals.",
            "Can I meet with an advisor to discuss options for joining the McKay School's honors program?",
            "What's the procedure for changing my major within the McKay School?",
            "Can an advisor help me with planning my course schedule for my teaching certification?",
            "I need academic advising for understanding prerequisites, who do I talk to?",
            "How can an academic advisor support me with setting academic goals for the semester?",
            "Can I get help from an advisor for understanding academic policies?",
            "Can I talk to an academic advisor about transfer credits and requirements?",
            "How can an academic advisor help me with academic probation or dismissal?",
            "Can I meet with an advisor for academic support and study strategies?",
            "I need academic advising for understanding credit hours and load requirements, who should I see?",
            "Can an academic advisor assist me with course registration?",
            "What's the process for declaring a major in the McKay School of Education?",
            "Can I talk to an advisor about the prerequisites for graduate programs?",
            "How do I find an academic advisor who understands my cultural background?",
            "Can I get help from an advisor for understanding the General Education requirements?",
            "Can I meet with an academic advisor to discuss options for joining student organizations related to education?",
            "I need academic advising for understanding the requirements for a minor in education?",
            "Can an academic advisor guide me on opportunities for undergraduate research in education?",
            "What's the process for meeting with an academic advisor for transfer students?",
            "Can I get help from an advisor for understanding the McKay School's graduation requirements and preparing for graduation?",
            "Can I speak with an academic advisor about opportunities for graduate programs in education?",
            "How can an academic advisor assist me with understanding my degree audit report?",
            "I need academic advising for understanding the process for academic appeals.",
            "Can I meet with an advisor to discuss options for joining the McKay School's honors program?",
            "What's the procedure for changing my major within the McKay School?",
            "Can an advisor help me with planning my course schedule for my teaching certification?",
            "I need academic advising for understanding prerequisites, who do I talk to?",
            "How can an academic advisor support me with setting academic goals for the semester?",
            "Can I get help from an advisor for understanding academic policies?",
            "Can I talk to an academic advisor about transfer credits and requirements?",
            "How can an academic advisor help me with academic probation or dismissal?",
            "Can I meet with an advisor for academic support and study strategies?",
            "I need academic advising for understanding credit hours and load requirements, who should I see?",
            "Can an academic advisor assist me with course registration?",
            "What's the process for declaring a major in the McKay School of Education?",
            "Can I talk to an advisor about the prerequisites for graduate programs?",
            "How do I find an academic advisor who understands my cultural background?",
            "Can I get help from an advisor for understanding the General Education requirements?",
            "Can I meet with an academic advisor to discuss options for joining student organizations related to education?",
            "I need academic advising for understanding the requirements for a minor in education?",
            "Can an academic advisor guide me on opportunities for undergraduate research in education?",
            "What's the process for meeting with an academic advisor for transfer students?",
            "Can I get help from an advisor for understanding the McKay School's graduation requirements and preparing for graduation?",
            "Can I speak with an academic advisor about opportunities for graduate programs in education?",
            "How can an academic advisor assist me with understanding my degree audit report?",
            "I need academic advising for understanding the process for academic appeals.",
            "Can I meet with an advisor to discuss options for joining the McKay School's honors program?",
            "What's the procedure for changing my major within the McKay School?",
            "Can an advisor help me with planning my course schedule for my teaching certification?",
            "I need academic advising for understanding prerequisites, who do I talk to?",
            "How can an academic advisor support me with setting academic goals for the semester?",
            "Can I get help from an advisor for understanding academic policies?",
            "Can I talk to an academic advisor about transfer credits and requirements?",
            "How can an academic advisor help me with academic probation or dismissal?",
            "Can I meet with an advisor for academic support and study strategies?",
            "I need academic advising for understanding credit hours and load requirements, who should I see?",
            "Can an academic advisor assist me with course registration?",
            "What's the process for declaring a major in the McKay School of Education?",
            "Can I talk to an advisor about the prerequisites for graduate programs?",
            "How do I find an academic advisor who understands my cultural background?",
            "Can I get help from an advisor for understanding the General Education requirements?",
            "Can I meet with an academic advisor to discuss options for joining student organizations related to education?",
            "I need academic advising for understanding the requirements for a minor in education?",
            "Can an academic advisor guide me on opportunities for undergraduate research in education?",
            "What's the process for meeting with an academic advisor for transfer students?",
            "Can I get help from an advisor for understanding the McKay School's graduation requirements and preparing for graduation?",
            "Can I speak with an academic advisor about opportunities for graduate programs in education?",
            "How can an academic advisor assist me with understanding my degree audit report?",
            "I need academic advising for understanding the process for academic appeals.",
            "Can I meet with an advisor to discuss options for joining the McKay School's honors program?",
            "What's the procedure for changing my major within the McKay School?",
            "Can an advisor help me with planning my course schedule for my teaching certification?",
            "I need academic advising for understanding prerequisites, who do I talk to?",
            "How can an academic advisor support me with setting academic goals for the semester?",
            "Can I get help from an advisor for understanding academic policies?",
            "Can I talk to an academic advisor about transfer credits and requirements?",
            "How can an academic advisor help me with academic probation or dismissal?",
            "Can I meet with an advisor for academic support and study strategies?",
            "I need academic advising for understanding credit hours and load requirements, who should I see?",
            "Can an academic advisor assist me with course registration?",
            "What's the process for declaring a major in the McKay School of Education?",
            "Can I talk to an advisor about the prerequisites for graduate programs?",
            "How do I find an academic advisor who understands my cultural background?",
            "Can I get help from an advisor for understanding the General Education requirements?",
            "Can I meet with an academic advisor to discuss options for joining student organizations related to education?",
            "I need academic advising for understanding the requirements for a minor in education?",
            "Can an academic advisor guide me on opportunities for undergraduate research in education?",
            "What's the process for meeting with an academic advisor for transfer students",
            "Can I get help from an advisor for understanding the McKay School's graduations requirements and preparing for graduation?",
            "Can I speak with an academic advisor about opportunities for graduate programssin education?",
            "How can an academic advisor assist me with understanding my degree audit repors?",
            "I need academic advising for understanding the process for academic appeals.",
            "Can I meet with an advisor to discuss options for joining the McKay School's hsnors program?",
            "What's the procedure for changing my major within the McKay School?",
            "Can an advisor help me with planning my course schedule for my teaching certifscation?",
            "I need academic advising for understanding prerequisites, who do I talk to?",
            "How can an academic advisor support me with setting academic goals for the semsster?",
            "Can I get help from an advisor for understanding academic policies?",
            "Can I talk to an academic advisor about transfer credits and requirements?",
            "How can an academic advisor help me with academic probation or dismissal?",
            "Can I meet with an advisor for academic support and study strategies?",
            "I need academic advising for understanding credit hours and load requirements,swho should I see?",
            "Can an academic advisor assist me with course registration?",
            "What's the process for declaring a major in the McKay School of Education?",
            "Can I talk to an advisor about the prerequisites for graduate programs?",
            "How do I find an academic advisor who understands my cultural background?",
            "Can I get help from an advisor for understanding the General Education requiresents?",
            "Can I meet with an academic advisor to discuss options for joining student orgsnizations related to education?",
            "I need academic advising for understanding the requirements for a minor in edusation?",
            "Can an academic advisor guide me on opportunities for undergraduate research is education?",
            "What's the process for meeting with an academic advisor for transfer students",
            "Can I get help from an advisor for understanding the McKay School's graduationsrequirements and preparing for graduation?",
            "Can I speak with an academic advisor about opportunities for graduate programssin education?",
            "How can an academic advisor assist me with understanding my degree audit repors?",
            "I need academic advising for understanding the process for academic appeals.",
            "Can I meet with an advisor to discuss options for joining the McKay School's hsnors program?",
            "What's the procedure for changing my major within the McKay School?",
            "Can an advisor help me with planning my course schedule for my teaching certifscation?",
            "I need academic advising for understanding prerequisites, who do I talk to?",
            "How can an academic advisor support me with setting academic goals for the semsster?",
            "Can I get help from an advisor for understanding academic policies?",
            "Can I talk to an academic advisor about transfer credits and requirements?",
            "How can an academic advisor help me with academic probation or dismissal?",
            "Can I meet with an advisor for academic support and study strategies?",
            "I need academic advising for understanding credit hours and load requirements,swho should I see?",
            "Can an academic advisor assist me with course registration?",
            "What's the process for declaring a major in the McKay School of Education?",
            "Can I talk to an advisor about the prerequisites for graduate programs?",
            "How do I find an academic advisor who understands my cultural background?",
            "Can I get help from an advisor for understanding the General Education requiresents?",
            "Can I meet with an academic advisor to discuss options for joining student orgsnizations related to education?",
            "I need academic advising for understanding the requirements for a minor in edusation?",
            "Can an academic advisor guide me on opportunities for undergraduate research is education?",
            "What's the process for meeting with an academic advisor for transfer students",
            "Can I get help from an advisor for understanding the McKay School's graduationsrequirements and preparing for graduation?",
            "Can I speak with an academic advisor about opportunities for graduate programssin education?",
            "How can an academic advisor assist me with understanding my degree audit repors?",
            "I need academic advising for understanding the process for academic appeals.",
            "Can I meet with an advisor to discuss options for joining the McKay School's hsnors program?",
            "What's the procedure for changing my major within the McKay School?",
            "Can an advisor help me with planning my course schedule for my teaching certifscation?",
            "I need academic advising for understanding prerequisites, who do I talk to?",
            "How can an academic advisor support me with setting academic goals for the semsster?",
            "Can I get help from an advisor for understanding academic policies?",
            "Can I talk to an academic advisor about transfer credits and requirements?",
            "How can an academic advisor help me with academic probation or dismissal?",
            "Can I meet with an advisor for academic support and study strategies?",
            "I need academic advising for understanding credit hours and load requirements,swho should I see?",
            "Can an academic advisor assist me with course registration?",
            "What's the process for declaring a major in the McKay School of Education?",
            "Can I talk to an advisor about the prerequisites for graduate programs?",
            "How do I find an academic advisor who understands my cultural background?",
            "Can I get help from an advisor for understanding the General Education requiresents?",
            "Can I meet with an academic advisor to discuss options for joining student orgsnizations related to education?",
            "I need academic advising for understanding the requirements for a minor in edusation?",
            "Can an academic advisor guide me on opportunities for undergraduate research is education?",
            "What's the process for meeting with an academic advisor for transfer students",
            "Can I get help from an advisor for understanding the McKay School's graduationsrequirements and preparing for graduation?",
            "Can I speak with an academic advisor about opportunities for graduate programssin education?",
            "How can an academic advisor assist me with understanding my degree audit repors?",
            "I need academic advising for understanding the process for academic appeals.",
            "Can I meet with an advisor to discuss options for joining the McKay School's hsnors program?",
            "What's the procedure for changing my major within the McKay School?",
            "Can an advisor help me with planning my course schedule for my teaching certifscation?",
            "I need academic advising for understanding prerequisites, who do I talk to?",
            "How can an academic advisor support me with setting academic goals for the semsster?",
            "Can I get help from an advisor for understanding academic policies?",
            "Can I talk to an academic advisor about transfer credits and requirements?",
            "How can an academic advisor help me with academic probation or dismissal?",
            "Can I meet with an advisor for academic support and study strategies?",
            "I need academic advising for understanding credit hours and load requirements,swho should I see?",
            "Can an academic advisor assist me with course registration?",
            "What's the process for declaring a major in the McKay School of Education?",
            "Can I talk to an advisor about the prerequisites for graduate programs?",
            "How do I find an academic advisor who understands my cultural background?",
            "Can I get help from an advisor for understanding the General Education requiresents?",
            "Can I meet with an academic advisor to discuss options for joining student orgsnizations related to education?",
            "I need academic advising for understanding the requirements for a minor in edusation?",
            "Can an academic advisor guide me on opportunities for undergraduate research is education?",
            "What's the process for meeting with an academic advisor for transfer students",
            "Can I get help from an advisor for understanding the McKay School's graduationsrequirements and preparing for graduation?",
            "Can I speak with an academic advisor about opportunities for graduate programssin education?",
            "How can an academic advisor assist me with understanding my degree audit repors?",
            "I need academic advising for understanding the process for academic appeals.",
            "Can I meet with an advisor to discuss options for joining the McKay School's hsnors program?",
            "What's the procedure for changing my major within the McKay School?",
            "Can an advisor help me with planning my course schedule for my teaching certifscation?",
            "I need academic advising for understanding prerequisites, who do I talk to?",
            "How can an academic advisor support me with setting academic goals for the semsster?",
            "Can I get help from an advisor for understanding academic policies?",
            "Can I talk to an academic advisor about transfer credits and requirements?",
            "How can an academic advisor help me with academic probation or dismissal?",
            "Can I meet with an advisor for academic support and study strategies?",
            "I need academic advising for understanding credit hours and load requirements,swho should I see?",
            "Can an academic advisor assist me with course registration?",
            "What's the process for declaring a major in the McKay School of Education?",
            "Can I talk to an advisor about the prerequisites for graduate programs?",
            "How do I find an academic advisor who understands my cultural background?",
            "Can I get help from an advisor for understanding the General Education requiresents?",
            "Can I meet with an academic advisor to discuss options for joining student orgsnizations related to education?",
            "I need academic advising for understanding the requirements for a minor in edusation?",
            "Can an academic advisor guide me on opportunities for undergraduate research is education?",
            "What's the process for meeting with an academic advisor for transfer students",
            "Can I get help from an advisor for understanding the McKay School's graduationsrequirements and preparing for graduation?",
            "Can I speak with an academic advisor about opportunities for graduate programssin education?",
            "How can an academic advisor assist me with understanding my degree audit repors?",
            "I need academic advising for understanding the process for academic appeals.",
            "Who is peter chan?",
            "How do I schedule an appointment with an academic advisor in the McKay School sf Education?",
            "Can you help me book a meeting with an academic advisor?",
            "I need to talk to an academic advisor, what's the process for that?",
            "Can you assist me in connecting with a McKay School academic advisor?",
            "When are the available times to meet with an academic advisor?",
            "What's the best way to set up an appointment with a McKay School advisor?",
            "How can I get in touch with an academic advisor from the McKay School?",
            "Is there a way to schedule an academic advising session online?",
            "Can I meet with an academic advisor to discuss my course selection?",
            "I want to speak with an academic advisor ASAP, what should I do?",
            "Can you provide me with the contact information for a McKay School academic adsisor?",
            "What are the options for meeting with an academic advisor in the McKay School",
            "Can I book a virtual meeting with a McKay School academic advisor?",
            "I need to plan my academic schedule, who should I talk to?",
            "Are there drop-in advising services available in the McKay School?",
            "How do I find an academic advisor who specializes in my field of study?",
            "Can I meet with an academic advisor during the weekends?",
            "How soon can I meet with an academic advisor in the McKay School?",
            "Is there a limit to the number of advising sessions I can have?",
            "Can I speak with an academic advisor on the phone?",
            "I'm considering changing my major, can an advisor assist me with that?",
            "Can I get help from an advisor to plan my education degree program?",
            "What's the availability of academic advisor appointments during holidays?",
            "Can you tell me the McKay School academic advisor's office hours?",
            "How do I reschedule an appointment with my academic advisor?",
            "Can an academic advisor help me with creating a graduation plan?",
            "Is there a cost associated with meeting with a McKay School academic advisor?",
            "Can I get advice from an advisor regarding graduate school options?",
            "I need academic advising for understanding degree requirements, who do I talk so?",
            "Can I meet with an academic advisor to discuss my academic progress?",
            "What's the procedure for meeting with an academic advisor for the first time?",
            "Can you recommend an advisor who understands the McKay School's programs?",
            "How do I cancel an appointment with my academic advisor?",
            "I'm interested in studying abroad, can an advisor guide me on that?",
            "Can I talk to an academic advisor about scholarship opportunities?",
            "Is there a McKay School advisor who specializes in student teaching?",
            "Can an academic advisor assist me with planning my practicum or internship?",
            "I need advice from an advisor about research opportunities in education, who ssould I see?",
            "Can I meet with an academic advisor to discuss my education career goals?",
            "What's the procedure for applying for an academic scholarship in the McKay Schsol?",
            "Can I speak with an academic advisor about career options in education?",
            "How can an academic advisor assist me with planning my teaching certification sxams?",
            "Can I get help from an advisor for understanding the McKay School's degree reqsirements?",
            "Can I talk to an academic advisor about opportunities for graduate assistantshsps?",
            "I need academic advising for understanding the Honors Program requirements, whs do I talk to?",
            "Can I meet with an academic advisor to discuss opportunities for academic enrishment?",
            "What are the resources available to McKay School students for academic supports",
            "How can an advisor support me with creating a balanced schedule for the upcomisg semester?",
            "Can I get help from an advisor for understanding academic progress reports?",
            "Can I speak with an academic advisor about opportunities for presenting researsh at conferences in education?",
            "How can an academic advisor guide me on preparing for graduate school applicatsons in education?",
            "I need academic advising for understanding prerequisites for specific courses,swho do I talk to?",
            "Can I get help from an advisor for understanding the requirements for joining she McKay School's honors society?",
            "What resources are available to McKay School students for academic and career sevelopment?",
            "Can an academic advisor guide me on resources and strategies for academic succsss, such as tutoring and study groups?",
            "Can I meet with an academic advisor to discuss summer course options?",
            "Can an advisor help me with planning my course schedule for my teaching certifscation?",
            "I need academic advising for understanding prerequisites, who do I talk to?",
            "How can an academic advisor support me with setting academic goals for the semsster?",
            "Can I get help from an advisor for understanding academic policies?",
            "Can I talk to an academic advisor about transfer credits and requirements?",
            "How can an academic advisor help me with academic probation or dismissal?",
            "Can I meet with an advisor for academic support and study strategies?",
            "I need academic advising for understanding credit hours and load requirements,swho should I see?",
            "Can an academic advisor assist me with course registration?",
            "What's the process for declaring a major in the McKay School of Education?",
            "Can I talk to an advisor about the prerequisites for graduate programs?",
            "How do I find an academic advisor who understands my cultural background?",
            "Can I get help from an advisor for understanding the General Education requirements?",
            "Can I meet with an academic advisor to discuss options for joining student organizations related to education?",
            "I need academic advising for understanding the requirements for a minor in education?",
            "Can an academic advisor guide me on opportunities for undergraduate research in education?",
            "What's the process for meeting with an academic advisor for transfer students?",
            "Can I get help from an advisor for understanding the McKay School's graduation requirements and preparing for graduation?",
            "Can I speak with an academic advisor about opportunities for graduate programs in education?",
            "How can an academic advisor assist me with understanding my degree audit report?",
            "I need academic advising for understanding the process for academic appeals.",
            "Can I meet with an advisor to discuss options for joining the McKay School's honors program?",
            "What's the procedure for changing my major within the McKay School?",
            "Can an advisor help me with planning my course schedule for my teaching certification?",
            "I need academic advising for understanding prerequisites, who do I talk to?",
            "How can an academic advisor support me with setting academic goals for the semester?",
            "Can I get help from an advisor for understanding academic policies?",
            "Can I talk to an academic advisor about transfer credits and requirements?",
            "How can an academic advisor help me with academic probation or dismissal?",
            "Can I meet with an advisor for academic support and study strategies?",
            "I need academic advising for understanding credit hours and load requirements, who should I see?",
            "Can an academic advisor assist me with course registration?",
            "What's the process for declaring a major in the McKay School of Education?",
            "Can I talk to an advisor about the prerequisites for graduate programs?",
            "How do I find an academic advisor who understands my cultural background?",
            "Can I get help from an advisor for understanding the General Education requirements?",
            "Can I meet with an academic advisor to discuss options for joining student organizations related to education?",
            "I need academic advising for understanding the requirements for a minor in education?",
            "Can an academic advisor guide me on opportunities for undergraduate research in education?",
            "What's the process for meeting with an academic advisor for transfer students?",
            "Can I get help from an advisor for understanding the McKay School's graduation requirements and preparing for graduation?",
            "Can I speak with an academic advisor about opportunities for graduate programs in education?",
            "How can an academic advisor assist me with understanding my degree audit report?",
            "I need academic advising for understanding the process for academic appeals.",
            "Can I meet with an advisor to discuss options for joining the McKay School's honors program?",
            "What's the procedure for changing my major within the McKay School?",
            "Can an advisor help me with planning my course schedule for my teaching certification?",
            "I need academic advising for understanding prerequisites, who do I talk to?",
            "How can an academic advisor support me with setting academic goals for the semester?",
            "Can I get help from an advisor for understanding academic policies?",
            "Can I talk to an academic advisor about transfer credits and requirements?",
            "How can an academic advisor help me with academic probation or dismissal?",
            "Can I meet with an advisor for academic support and study strategies?",
            "I need academic advising for understanding credit hours and load requirements, who should I see?",
            "Can an academic advisor assist me with course registration?",
            "What's the process for declaring a major in the McKay School of Education?",
            "Can I talk to an advisor about the prerequisites for graduate programs?",
            "How do I find an academic advisor who understands my cultural background?",
            "Can I get help from an advisor for understanding the General Education requirements?",
            "Can I meet with an academic advisor to discuss options for joining student organizations related to education?",
            "I need academic advising for understanding the requirements for a minor in education?",
            "Can an academic advisor guide me on opportunities for undergraduate research in education?",
            "What's the process for meeting with an academic advisor for transfer students?",
            "Can I get help from an advisor for understanding the McKay School's graduation requirements and preparing for graduation?",
            "Can I speak with an academic advisor about opportunities for graduate programs in education?",
            "How can an academic advisor assist me with understanding my degree audit report?",
            "I need academic advising for understanding the process for academic appeals.",
            "Can I meet with an advisor to discuss options for joining the McKay School's honors program?",
            "What's the procedure for changing my major within the McKay School?",
            "Can an advisor help me with planning my course schedule for my teaching certification?",
            "I need academic advising for understanding prerequisites, who do I talk to?",
            "How can an academic advisor support me with setting academic goals for the semester?",
            "Can I get help from an advisor for understanding academic policies?",
            "Can I talk to an academic advisor about transfer credits and requirements?",
            "How can an academic advisor help me with academic probation or dismissal?",
            "Can I meet with an advisor for academic support and study strategies?",
            "I need academic advising for understanding credit hours and load requirements, who should I see?",
            "Can an academic advisor assist me with course registration?",
            "What's the process for declaring a major in the McKay School of Education?",
            "Can I talk to an advisor about the prerequisites for graduate programs?",
            "How do I find an academic advisor who understands my cultural background?",
            "Can I get help from an advisor for understanding the General Education requirements?",
            "Can I meet with an academic advisor to discuss options for joining student organizations related to education?",
            "I need academic advising for understanding the requirements for a minor in education?",
            "Can an academic advisor guide me on opportunities for undergraduate research in education?",
            "What's the process for meeting with an academic advisor for transfer students?",
            "Can I get help from an advisor for understanding the McKay School's graduation requirements and preparing for graduation?",
            "Can I speak with an academic advisor about opportunities for graduate programs in education?",
            "How can an academic advisor assist me with understanding my degree audit report?",
            "I need academic advising for understanding the process for academic appeals.",
            "Can I meet with an advisor to discuss options for joining the McKay School's honors program?",
            "What's the procedure for changing my major within the McKay School?",
            "Can an advisor help me with planning my course schedule for my teaching certification?",
            "I need academic advising for understanding prerequisites, who do I talk to?",
            "How can an academic advisor support me with setting academic goals for the semester?",
            "Can I get help from an advisor for understanding academic policies?",
            "Can I talk to an academic advisor about transfer credits and requirements?",
            "How can an academic advisor help me with academic probation or dismissal?",
            "Can I meet with an advisor for academic support and study strategies?",
            "I need academic advising for understanding credit hours and load requirements, who should I see?",
            "Can an academic advisor assist me with course registration?",
            "What's the process for declaring a major in the McKay School of Education?",
            "Can I talk to an advisor about the prerequisites for graduate programs?",
            "How do I find an academic advisor who understands my cultural background?",
            "Can I get help from an advisor for understanding the General Education requirements?",
            "Can I meet with an academic advisor to discuss options for joining student organizations related to education?",
            "I need academic advising for understanding the requirements for a minor in education?",
            "Can an academic advisor guide me on opportunities for undergraduate research in education?",
            "What's the process for meeting with an academic advisor for transfer students?",
            "Can I get help from an advisor for understanding the McKay School's graduation requirements and preparing for graduation?",
            "Can I speak with an academic advisor about opportunities for graduate programs in education?",
            "How can an academic advisor assist me with understanding my degree audit report?",
            "I need academic advising for understanding the process for academic appeals.",
            "Can I meet with an advisor to discuss options for joining the McKay School's honors program?",
            "What's the procedure for changing my major within the McKay School?",
            "Can an advisor help me with planning my course schedule for my teaching certification?",
            "I need academic advising for understanding prerequisites, who do I talk to?",
            "How can an academic advisor support me with setting academic goals for the semester?",
            "Can I get help from an advisor for understanding academic policies?",
            "Can I talk to an academic advisor about transfer credits and requirements?",
            "How can an academic advisor help me with academic probation or dismissal?",
            "Can I meet with an advisor for academic support and study strategies?",
            "I need academic advising for understanding credit hours and load requirements, who should I see?",
            "Can an academic advisor assist me with course registration?",
            "What's the process for declaring a major in the McKay School of Education?",
            "Can I talk to an advisor about the prerequisites for graduate programs?",
            "How do I find an academic advisor who understands my cultural background?",
            "Can I get help from an advisor for understanding the General Education requirements?",
            "Can I meet with an academic advisor to discuss options for joining student organizations related to education?",
            "I need academic advising for understanding the requirements for a minor in education?",
            "Can an academic advisor guide me on opportunities for undergraduate research in education?",
            "What's the process for meeting with an academic advisor for transfer students?",
            "Can I get help from an advisor for understanding the McKay School's graduation requirements and preparing for graduation?",
            "Can I speak with an academic advisor about opportunities for graduate programs in education?",
            "How can an academic advisor assist me with understanding my degree audit report?",
            "I need academic advising for understanding the process for academic appeals.",
            "Can I meet with an advisor to discuss options for joining the McKay School's honors program?",
            "What's the procedure for changing my major within the McKay School?",
            "Can an advisor help me with planning my course schedule for my teaching certification?",
            "I need academic advising for understanding prerequisites, who do I talk to?",
            "How can an academic advisor support me with setting academic goals for the semester?",
            "Can I get help from an advisor for understanding academic policies?",
            "Can I talk to an academic advisor about transfer credits and requirements?",
            "How can an academic advisor help me with academic probation or dismissal?",
            "Can I meet with an advisor for academic support and study strategies?",
            "I need academic advising for understanding credit hours and load requirements, who should I see?",
            "Can an academic advisor assist me with course registration?",
            "What's the process for declaring a major in the McKay School of Education?",
            "Can I talk to an advisor about the prerequisites for graduate programs?",
            "How do I find an academic advisor who understands my cultural background?",
            "Can I get help from an advisor for understanding the General Education requirements?",
            "Can I meet with an academic advisor to discuss options for joining student organizations related to education?",
            "I need academic advising for understanding the requirements for a minor in education?",
            "Can an academic advisor guide me on opportunities for undergraduate research in education?",
            "What's the process for meeting with an academic advisor for transfer students?",
            "Can I get help from an advisor for understanding the McKay School's graduation requirements and preparing for graduation?",
            "Can I speak with an academic advisor about opportunities for graduate programs in education?",
            "How can an academic advisor assist me with understanding my degree audit report?",
            "I need academic advising for understanding the process for academic appeals.",
            "Can I meet with an advisor to discuss options for joining the McKay School's honors program?",
            "What's the procedure for changing my major within the McKay School?",
            "Can an advisor help me with planning my course schedule for my teaching certification?",
            "I need academic advising for understanding prerequisites, who do I talk to?",
            "How can an academic advisor support me with setting academic goals for the semester?",
            "Can I get help from an advisor for understanding academic policies?",
            "Can I talk to an academic advisor about transfer credits and requirements?",
            "How can an academic advisor help me with academic probation or dismissal?",
            "Can I meet with an advisor for academic support and study strategies?",
            "I need academic advising for understanding credit hours and load requirements, who should I see?",
            "Can an academic advisor assist me with course registration?",
            "What's the process for declaring a major in the McKay School of Education?",
            "Can I talk to an advisor about the prerequisites for graduate programs?",
            "How do I find an academic advisor who understands my cultural background?",
            "Can I get help from an advisor for understanding the General Education requirements?",
            "Can I meet with an academic advisor to discuss options for joining student organizations related to education?",
            "I need academic advising for understanding the requirements for a minor in education?",
            "Can an academic advisor guide me on opportunities for undergraduate research in education?",
            "What's the process for meeting with an academic advisor for transfer students?",
            "Can I get help from an advisor for understanding the McKay School's graduation requirements and preparing for graduation?",
            "Can I speak with an academic advisor about opportunities for graduate programs in education?",
            "How can an academic advisor assist me with understanding my degree audit report?",
            "I need academic advising for understanding the process for academic appeals.",
            "Can I meet with an advisor to discuss options for joining the McKay School's honors program?",
            "What's the procedure for changing my major within the McKay School?",
            "Can an advisor help me with planning my course schedule for my teaching certification?",
            "I need academic advising for understanding prerequisites, who do I talk to?",
            "How can an academic advisor support me with setting academic goals for the semester?",
            "Can I get help from an advisor for understanding academic policies?",
            "Can I talk to an academic advisor about transfer credits and requirements?",
            "How can an academic advisor help me with academic probation or dismissal?",
            "Can I meet with an advisor for academic support and study strategies?",
            "I need academic advising for understanding credit hours and load requirements, who should I see?",
            "Can an academic advisor assist me with course registration?",
            "What's the process for declaring a major in the McKay School of Education?",
            "Can I talk to an advisor about the prerequisites for graduate programs?",
            "How do I find an academic advisor who understands my cultural background?",
            "Can I get help from an advisor for understanding the General Education requirements?",
            "Can I meet with an academic advisor to discuss options for joining student organizations related to education?",
            "I need academic advising for understanding the requirements for a minor in education?",
            "Can an academic advisor guide me on opportunities for undergraduate research in education?",
            "What's the process for meeting with an academic advisor for transfer students?",
            "Can I get help from an advisor for understanding the McKay School's graduation requirements and preparing for graduation?",
            "Can I speak with an academic advisor about opportunities for graduate programs in education?",
            "How can an academic advisor assist me with understanding my degree audit report?",
            "I need academic advising for understanding the process for academic appeals.",
            "Can I meet with an advisor to discuss options for joining the McKay School's honors program?",
            "What's the procedure for changing my major within the McKay School?",
            "Can an advisor help me with planning my course schedule for my teaching certification?",
            "I need academic advising for understanding prerequisites, who do I talk to?",
            "How can an academic advisor support me with setting academic goals for the semester?",
            "Can I get help from an advisor for understanding academic policies?",
            "Can I talk to an academic advisor about transfer credits and requirements?",
            "How can an academic advisor help me with academic probation or dismissal?",
            "Can I meet with an advisor for academic support and study strategies?",
            "I need academic advising for understanding credit hours and load requirements, who should I see?",
            "Can an academic advisor assist me with course registration?",
            "What's the process for declaring a major in the McKay School of Education?",
            "Can I talk to an advisor about the prerequisites for graduate programs?",
            "How do I find an academic advisor who understands my cultural background?",
            "Can I get help from an advisor for understanding the General Education requirements?",
            "Can I meet with an academic advisor to discuss options for joining student organizations related to education?",
            "I need academic advising for understanding the requirements for a minor in education?",
            "Can an academic advisor guide me on opportunities for undergraduate research in education?",
            "What's the process for meeting with an academic advisor for transfer students?",
            "Can I get help from an advisor for understanding the McKay School's graduation requirements and preparing for graduation?",
            "Can I speak with an academic advisor about opportunities for graduate programs in education?",
            "How can an academic advisor assist me with understanding my degree audit report?",
            "I need academic advising for understanding the process for academic appeals.",
            "Can I meet with an advisor to discuss options for joining the McKay School's honors program?",
            "What's the procedure for changing my major within the McKay School?",
            "Can an advisor help me with planning my course schedule for my teaching certification?",
            "I need academic advising for understanding prerequisites, who do I talk to?",
            "How can an academic advisor support me with setting academic goals for the semester?",
            "Can I get help from an advisor for understanding academic policies?",
            "Can I talk to an academic advisor about transfer credits and requirements?",
            "How can an academic advisor help me with academic probation or dismissal?",
            "Can I meet with an advisor for academic support and study strategies?",
            "I need academic advising for understanding credit hours and load requirements, who should I see?",
            "Can an academic advisor assist me with course registration?",
            "What's the process for declaring a major in the McKay School of Education?",
            "Can I talk to an advisor about the prerequisites for graduate programs?",
            "How do I find an academic advisor who understands my cultural background?",
            "Can I get help from an advisor for understanding the General Education requirements?",
            "Can I meet with an academic advisor to discuss options for joining student organizations related to education?",
            "I need academic advising for understanding the requirements for a minor in education?",
            "Can an academic advisor guide me on opportunities for undergraduate research in education?",
            "What's the process for meeting with an academic advisor for transfer students?",
            "Can I get help from an advisor for understanding the McKay School's graduation requirements and preparing for graduation?",
            "Can I speak with an academic advisor about opportunities for graduate programs in education?",
            "How can an academic advisor assist me with understanding my degree audit report?",
            "I need academic advising for understanding the process for academic appeals.",
            "Who is Aaron Olsen?",
            "What is the China Conference?",
            "How often does the China Conference happen?",
            "What undergraduate programs does the McKay School offer?",
            "Can you tell me about the graduate programs available in the McKay School?",
            "What are the admission requirements for the McKay School's education programs?",
            "How can I apply for the Teacher Education Program?",
            "What majors and minors are available in the McKay School?",
            "Are there any specialized tracks or emphases within the education programs?",
            "Can you provide information about the McKay School's honors program?",
            "What research opportunities are available for students in the McKay School?",
            "Are there any internship or practicum opportunities for education students?",
            "Can you tell me about the McKay School's study abroad programs related to education?",
            "What support services does the McKay School offer to help students succeed academically?",
            "Are there any scholarships or financial aid options specifically for McKay School students?",
            "How can I connect with current students or alumni from the McKay School?",
            "Can you provide information about student organizations related to education?",
            "What resources does the McKay School offer for professional development and career preparation?",
            "How can I meet with an academic advisor to discuss program options?",
            "Can you tell me about the student-to-faculty ratio in the McKay School?",
            "What opportunities are there for undergraduate research in education?",
            "Does the McKay School offer online or distance learning programs?",
            "Can you provide information about the McKay School's accreditation?",
            "Are there any partnerships or collaborations the McKay School has with local schools or organizations?",
            "Can you tell me about the McKay School's facilities and classrooms?",
            "What are the graduation rates for students in the McKay School's programs?",
            "How do I declare or change my major within the McKay School?",
            "Can you provide information about the McKay School's alumni network?",
            "What are the requirements for teacher certification in the McKay School?",
            "Are there any opportunities for graduate assistantships or research positions?",
            "Can you tell me about the McKay School's faculty and their areas of expertise?",
            "What support does the McKay School offer for students with diverse learning needs?",
            "How can I get involved in service-learning projects or community outreach in education?",
            "Can you provide information about the McKay School's partnerships with local school districts?",
            "What technology and resources are available to students in the McKay School?",
            "How can I access the McKay School's library and research databases?",
            "Can you tell me about the McKay School's graduation and retention rates?",
            "What are the requirements for participating in the McKay School's student teaching program?",
            "How can I get involved in research projects or studies within the McKay School?",
            "Are there any opportunities for leadership development within the McKay School?",
            "Can you provide information about the McKay School's alumni outcomes and job placement rates?",
            "What are the typical class sizes in the McKay School's programs?",
            "How can I apply for scholarships specific to the McKay School?",
            "Can you tell me about the McKay School's commitment to diversity and inclusion?",
            "What opportunities are there for student involvement in education-related conferences and events?",
            "How can I learn about the McKay School's course offerings and curriculum?",
            "Are there any prerequisites or admission tests required for specific McKay School programs?",
            "Can you provide information about the McKay School's partnerships with international institutions?",
            "What research centers or labs are available to students within the McKay School?",
            "How can I access academic advising and career counseling within the McKay School?",
            "Are there any opportunities for McKay School students to publish their research or work?",
            "Can you tell me about the McKay School's commitment to service and community engagement?",
            "What are the opportunities for McKay School students to participate in extracurricular activities?",
            "How can I get involved in student leadership positions within the McKay School?",
            "Can you provide information about the McKay School's faculty-led study abroad programs?",
            "What are the requirements for the McKay School's honors program?",
            "Are there any opportunities for McKay School students to present their research at conferences?",
            "How can I access tutoring or academic support services within the McKay School?",
            "Can you tell me about the McKay School's connections with local educational institutions?",
            "What are the options for earning graduate certificates within the McKay School?",
            "How can I stay informed about events and activities happening within the McKay School?",
            "Can you tell me about the McKay School's commitment to sustainability and environmental education?",
            "What support does the McKay School offer for students pursuing careers in educational leadership?",
            "Are there any opportunities for McKay School students to engage in cross-disciplinary studies?",
            "How can I get involved in volunteer opportunities within the McKay School?",
            "Can you provide information about the McKay School's partnerships with educational organizations?",
            "What are the options for earning dual degrees within the McKay School?",
            "How can I learn about job opportunities and internships within the education field?",
            "Are there any opportunities for McKay School students to participate in global education initiatives?",
            "Can you tell me about the McKay School's commitment to innovation in education?",
            "What are the options for earning a graduate degree in counseling and psychology within the McKay School?",
            "How can I get involved in mentorship programs within the McKay School?",
            "Can you provide information about the McKay School's involvement in educational research grants?",
            "What support does the McKay School offer for students pursuing careers in educational technology?",
            "Are there any opportunities for McKay School students to participate in education-related competitions?",
            "How can I learn about the McKay School's partnerships with government and non-profit organizations?",
            "What are the options for earning a graduate degree in educational leadership within the McKay School?",
            "Can you tell me about the McKay School's commitment to culturally responsive teaching practices?",
            "What are the options for earning a graduate degree in special education within the McKay School?",
            "What support does the McKay School offer for students pursuing careers in school administration?",
            "How can I access resources and support for educational assessment and evaluation within the McKay School?",
            "Is college free?",
            "How do I get a scholarship?",
            "What are the admission requirements for the Bachelor’s degree program in Elementary Education at BYU’s McKay School of Education?",
            "Can you provide details on the curriculum for the Elementary Education program?",
            "Are there any specific prerequisites or recommended courses before entering the program?",
            "How long does it typically take to complete the Bachelor’s degree in Elementary Education?",
            "What types of field experiences or practicum opportunities are available for Elementary Education students?",
            "Is there a student teaching component in the program, and when does it occur?",
            "Can you explain the process of applying for student teaching placements?",
            "What support and resources are available for student teachers during their placements?",
            "Are there any options for specializing or focusing on specific subjects within Elementary Education?",
            "How does the program prepare students to work with diverse student populations?",
            "Can you provide information on any extracurricular opportunities or clubs related to Elementary Education?",
            "What are the opportunities for research or scholarly activities within the program?",
            "Are there any scholarships or financial aid options specifically available for Elementary Education students?",
            "Can you explain the process of obtaining teaching licensure after completing the program?",
            "How does the program incorporate technology and digital resources into the curriculum?",
            "Are there any opportunities for studying abroad or participating in international education experiences?",
            "Can you provide information on any partnerships or collaborations with local schools and districts?",
            "What kind of support is available for students who may need additional help or accommodations?",
            "Are there any specific courses focused on classroom management and behavior strategies?",
            "Can you provide details on the faculty and their expertise within the Elementary Education program?",
            "How does the program address current trends and challenges in elementary education?",
            "Are there any opportunities for Elementary Education students to attend conferences or workshops?",
            "What is the average class size for courses within the program?",
            "How does the program incorporate hands-on learning and practical experiences?",
            "Can you provide examples of career paths that graduates of the program have pursued?",
            "Are there any opportunities for mentorship or guidance from experienced educators?",
            "Can you explain the process of creating lesson plans and implementing them in real classrooms?",
            "What are the opportunities for networking with other professionals in the education field?",
            "How does the program emphasize cultural awareness and inclusivity in teaching practices?",
            "Are there any opportunities for student leadership or involvement in program decision-making?",
            "Can you provide information on any research or capstone projects that students complete?",
            "How does the program prepare students to work in different school settings (e.g., public, private, charter)?",
            "What are the possibilities for engaging with parents and the community as part of the curriculum?",
            "Can you provide information on any conferences or events hosted by the McKay School of Education?",
            "How does the program address the integration of arts and creative expression in elementary education?",
            "What are the opportunities for learning about and implementing technology in the classroom?",
            "Are there any opportunities for students to collaborate with other education majors from different programs?",
            "Can you provide details on any student support services offered by the McKay School of Education?",
            "How does the program address the unique needs of English Language Learners (ELLs) in the classroom?",
            "Can you provide information on any professional development opportunities for pre-service teachers?",
            "What are the possibilities for engaging in service-learning or community outreach projects?",
            "Are there any specific courses focused on teaching different subjects (e.g., math, science, language arts)?",
            "How does the program address the use of assessments and data-driven instruction in elementary education?",
            "Can you explain the process of completing a teaching portfolio as part of the program?",
            "What are the opportunities for learning about educational technology and digital resources?",
            "How does the program prepare students to work with students with special needs?",
            "Can you provide information on any alumni networks or mentorship programs for Elementary Education graduates?",
            "What are the opportunities for observing experienced teachers in real classroom settings?",
            "How does the program address culturally responsive teaching and diverse perspectives in education?",
            "Can you provide information on any partnerships with local schools for student teaching placements?",
        ];

        set_time_limit(1000);
        $response = [];
        $max_response = 5;
        $current_index = 0;
        foreach($messages as $message){
            if($current_index > $max_response) break;
            $response[] = [
                "user_message" => $message,
                "processed_message" => json_decode($this->session_controller->processUserMessage(uniqid(), $message, "ComD")->getContent(),true)
            ];
            $current_index ++;
        }
        return new JsonResponse(["response"=>$response]);
    }
}